### ISSUE TITLE
unit is None for constant variables with quick unit

### ISSUE THREAD

**Issue by martinjrobins** [myokit/myokit#982] opened 2023-06-08 16:01 UTC
After parsing the following mmt file into a `Model`, what should the units be for `tlag` and `ka`? I was expecting [h] and [1/h], but `v.unit()` returns None?

```mmt
[[model]]

[environment]
t = 0 bind time
    
[PKCompartment]

tlag = 1 [h]
	desc: absorption lag time from extravasc compartment (implementation tbd)

ka = 1 [1/h]
    desc: first order absorption rate constant  
```

**Comment by MichaelClerx** [comment] 2023-06-08 16:07
Another reason I've not implemented it yet is that I don't know how to output it:
```
parse('''
x = 5 [mV]
y = 6 [mV]
    in [mV]
''').code() 
```
would produce either
```
x = 5 [mV]
y = 6 [mV]
```
or
```
x = 5 [mV]
    in [mV]
y = 6 [mV]
    in [mV]
```

**Comment by MichaelClerx** [comment] 2023-06-08 16:08
All solvable! But not sure if it feels right 😄

**Comment by martinjrobins** [comment] 2023-06-08 16:10
What I was expecting was not that [h] would be attributed to the tlag variable, but that the rhs expression would have units [h], and when this was assigned, then `tlag` would pick up this unit as well since no unit was provided (for checking)

So the rule would be: A variable is either assigned a unit using the `in` keyword, or assigned a unit based on the unit of the rhs expression

**Comment by MichaelClerx** [comment] 2023-06-08 16:12
In that case, would you expect:
```
v = component.add_variable('v')
v.set_rhs('1 [V]')  # v gets units V
v.set_rhs('2 [A'])
```
to
1. Create a variable v with units V and RHS "2 [A]", or
2. Create a variable v with units A and RHS "2 [A]" because it's remembered that it was only inferring its unit?

**Comment by MichaelClerx** [comment] 2023-06-08 16:14
or I guess

3. Create a variable v with no units and RHS "2 [A]", but have `.unit()` return `A` anyway? Might necessitate some extra argument to `unit()` to make it return the explicitly set unit only?

**Comment by martinjrobins** [comment] 2023-06-08 16:16
I would expect something like this:

```
v = component.add_variable('v') # v has no unit
v.set_rhs('1 [V]')  # v gets units V # v has unit [V]
v.set_rhs('2 [A']) # raises error due to incompatible units
```

I guess it depends if you want units to be "infectious" or not. tbh I can see advantages either way. You way is more explicit rather than implicit.

**Comment by MichaelClerx** [comment] 2024-07-17 16:11
Closing as duplicate of #650

**Closed by MichaelClerx** 2024-07-17 16:11 UTC
Labels: feature, question
